//
//  CJGSwitchChain.m
//  ShareManager
//
//  Created by Chen Jinguo on 2022/12/29.
//

#import "CJGSwitchChain.h"

#define CJGCATEGORY_CHAIN_SWITCH_IMPLEMENTATION(CJGMethod,CJGParaType) CJGCATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(CJGMethod,CJGParaType, CJGSwitchChain *,UISwitch)
@implementation CJGSwitchChain

CJGCATEGORY_CHAIN_SWITCH_IMPLEMENTATION(on, BOOL);
CJGCATEGORY_CHAIN_SWITCH_IMPLEMENTATION(onTintColor, UIColor *);
CJGCATEGORY_CHAIN_SWITCH_IMPLEMENTATION(thumbTintColor, UIColor *);

CJGCATEGORY_CHAIN_SWITCH_IMPLEMENTATION(onImage, UIImage *);
CJGCATEGORY_CHAIN_SWITCH_IMPLEMENTATION(offImage, UIImage *);

@end
CJGCATEGORY_VIEW_IMPLEMENTATION(UISwitch, CJGSwitchChain)
#undef CJGCATEGORY_CHAIN_SWITCH_IMPLEMENTATION
