//
//  CJGTextViewChain.m
//  ShareManager
//
//  Created by Chen Jinguo on 2022/12/29.
//

#import "CJGTextViewChain.h"
#define CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(CJGMethod,CJGParaType) CJGCATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(CJGMethod,CJGParaType, CJGTextViewChain *,UITextView)

@implementation CJGTextViewChain
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(delegate, id<UITextViewDelegate>);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(text, NSString *);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(font, UIFont *);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(textColor, UIColor *);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(textAlignment, NSTextAlignment);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(selectedRange, NSRange);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(editable, BOOL);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(selectable, BOOL);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(dataDetectorTypes, UIDataDetectorTypes);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(keyboardType, UIKeyboardType);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(allowsEditingTextAttributes, BOOL);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(attributedText, NSAttributedString *);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(typingAttributes, NSDictionary *);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(clearsOnInsertion, BOOL);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(textContainerInset, UIEdgeInsets);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(linkTextAttributes, NSDictionary *);
#pragma mark - UITextInputTraits -
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(autocapitalizationType, UITextAutocapitalizationType);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(autocorrectionType, UITextAutocorrectionType)
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(spellCheckingType, UITextSpellCheckingType)

CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(keyboardAppearance, UIKeyboardAppearance);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(returnKeyType, UIReturnKeyType);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(enablesReturnKeyAutomatically, BOOL);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(secureTextEntry, BOOL);
CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION(textContentType, UITextContentType);
@end
CJGCATEGORY_VIEW_IMPLEMENTATION(UITextView, CJGTextViewChain)

#undef CJGCATEGORY_CHAIN_TEXT_IMPLEMENTATION
