use_frameworks!

platform :ios, '11.0'
target 'CJGChainProgramming_Example' do
  pod 'Masonry'
  pod 'CJGChainProgramming', :path => '../'

  target 'CJGChainProgramming_Tests' do
    inherit! :search_paths

    
  end
end
