//
//  CJGEmiiterLayerChain.m
//  ShareManager
//
//  Created by Chen Jinguo on 2022/12/29.
//

#import "CJGEmiiterLayerChain.h"

#define CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(CJGMethod,CJGParaType) CJGCATEGORY_CHAIN_LAYERCLASS_IMPLEMENTATION(CJGMethod,CJGParaType, CJGEmiiterLayerChain *, CAEmitterLayer)

@implementation CJGEmiiterLayerChain
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterCells, NSArray<CAEmitterCell *> *)
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(birthRate, float)
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(lifetime, float)
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterPosition, CGPoint)
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterZPosition, CGFloat)
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterSize, CGSize)
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterDepth, CGFloat)

#ifdef __IPHONE_12_0
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterShape, CAEmitterLayerEmitterShape)
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterMode, CAEmitterLayerEmitterMode)
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(renderMode, CAEmitterLayerRenderMode)
#endif
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(preservesDepth, BOOL)
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(velocity, float)
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(scale, float)
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(spin, float)
CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(seed, unsigned int)
@end
CJGCATEGORY_LAYER_IMPLEMENTATION(CAEmitterLayer, CJGEmiiterLayerChain)
#undef CJGCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION
