//
//  CJGTiledLayerChain.m
//  ShareManager
//
//  Created by Chen Jinguo on 2022/12/29.
//

#import "CJGTiledLayerChain.h"
#define CJGCATEGORY_CHAIN_TILEDLAYER_IMPLEMENTATION(CJGMethod,CJGParaType) CJGCATEGORY_CHAIN_LAYERCLASS_IMPLEMENTATION(CJGMethod,CJGParaType, CJGTiledLayerChain *, CATiledLayer)

@implementation CJGTiledLayerChain
CJGCATEGORY_CHAIN_TILEDLAYER_IMPLEMENTATION(levelsOfDetail, size_t)
CJGCATEGORY_CHAIN_TILEDLAYER_IMPLEMENTATION(levelsOfDetailBias,size_t)
CJGCATEGORY_CHAIN_TILEDLAYER_IMPLEMENTATION(tileSize,CGSize)
@end
CJGCATEGORY_LAYER_IMPLEMENTATION(CATiledLayer, CJGTiledLayerChain)
#undef CJGCATEGORY_CHAIN_TILEDLAYER_IMPLEMENTATION
